# -*- coding: utf-8 -*-
"""streamlitBasic.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143JqHjFeYeKOsxr60u40MFg_QqvX9WqV
"""

import streamlit as st
st.title("Helo, Streamlit")
name = st.text_input("Enter your name:")
email = st.text_input("Enter your email:")
password = st.text_input("Enter your password:", type="password")
if st.button("Submit"):
    st.write("Name:", name)
    st.write("Email:", email)
    st.write("Password:", password)