# -*- coding: utf-8 -*-
"""streamlit_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtsA_1DoBlbLxIK7kddy0DXRbs-dkwPv
"""

import streamlit as st

#Title of the app
st.title("Hello, Streamlit!")

#Simple input and output
name = st.text_input("Enter your name:")
if st.button("Submit"):
  st.write(f"Hello, {name}!")